---
- name: enable ansible repo
  community.general.rhsm_repository:
    name: ansible-2-for-rhel-8-x86_64-rpms
    state: enabled

- name: install ansible
  ansible.builtin.dnf:
    name: ansible
    state: latest